version: '2'
services:
  minio-server:
    tty: true
    image: mschneider82/alpine-minio:latest
    volumes:
      - minio-data:/data/disk0
    ports:
      - 9000:9000
volumes:
  minio-data:
    driver: local
